### ISSUE TITLE
Shorthand to add "example" instead of "default" value?

### ISSUE THREAD

**Issue by DonMartin76** [readmeio/swagger-inline#16]
It would be nice to be able specify an `example` for a parameter instead of or in addition to specifying the `default` value via the `whatever=defaultvalue` syntax.

I don't have a really good idea how that syntax should look like though.

It just nags me that the values I pass in as parameter values are set as default, when I'd rather want to have them as examples.

**Comment by gkoberger** [comment]
Hey! I like this in theory (since I think examples are incredibly important), but I'm also not sure what syntax to use. Shorthand was written for Swagger 2, before examples were even a thing, which is why I went with `whatever=default`.

A few potential options:

  1. A setting somewhere that lets you choose between default and example in that syntax (I don't love this)
  2. Something like `name=default@example` (So, `limit=10@5` or `name@greg`), which is a bit confusing
  3. In the description, extracting `(ex: 3)`, so something like `limit=10 The number of pages (ex: 5)`

Anything else come to mind?

**Comment by DonMartin76** [comment]
Like this perhaps:

```
- (path) tenantId ex=5bc8873b2264ca9989fd2d96 {String} The ID of the tenant to operate on
```

Using both default and example would then be:

```
- (path) tenantId=5bc8873b2264ca9989fd2d96 ex=5bc8873b2264ca9989fd2d96 {String} The ID of the tenant to operate on
```

Or, `example=` instead of `ex`, which is a little more verbose, but perhaps less confusing. 

This would be compatible with the previous syntax, and it would make it quite easy to add an example. Plus it's quite simple to change the previous default values to examples should you wish to do so.

**Comment by Fabii23** [comment]
Where can I find documentation on adding a payload example, or info about request parameters ?

**Comment by erunion** [comment]
@Fabii23 The `swagger-inline` shorthand syntax doesn't support examples or proper request bodies, but it does support full OpenAPI and Swagger definitions so you can write those in your docblocks. Check out https://github.com/readmeio/swagger-inline/blob/master/__tests__/__fixtures__/project-openapi/api.js for an example.
